
---
- name: backup database
  hosts: database
  become: true
  become_user: root
  connection: database
  gather_facts: no
  
  roles:
    - mysql
    
  tasks:
    - name: touch file
      template:
        src: mysql
        dest: /etc/mysql.sh
        owner: root
        group: root
        mode: 0777


    - name: replace host
      replace:
        path: /etc/mysql.sh
        regexp: '@host'
        replace: "{{ item }}"
      with_inventory_hostnames:
        - database


    - name: replace password
      replace:
        path: /etc/mysql.sh
        regexp: '@password'
        replace: "{{ password }}"

    - name: configure crontab
      shell: echo "*/1 *   * * *   root    bash /etc/mysql.sh" >> crontab
      args:
        chdir: /etc

    - name: run shell
      shell: sudo bash mysql.sh
      args:
        chdir: /etc

    - name: restart crontab
      become: yes
      service:
        name: cron
        state: restarted
